### ISSUE TITLE
Add package to AUR for arch linux.

### ISSUE THREAD

**Issue by croutch** [brainpower/bp-nfoview#1]
Hello brainpower.
I was just looking for a new nfoviwer for my kde plasma desktop( i use nfoviewer for gtk3 before). And just installed yours and it looks very nice. Put it on AUR so more people can find it.
And it would be nice if you could add clickable links in nfos.
thanks 
croutch

**Comment by brainpower** [comment]
Fixed!
AUR package located at: https://aur.archlinux.org/packages/bp-nfoview/
Links are now detected and are clickable.
