### ISSUE TITLE
error when building from AUR

### ISSUE THREAD

**Issue by 0-st** [brainpower/bp-nfoview#2]
[ 25%] Building CXX object src/CMakeFiles/bp-nfoview.dir/bp-nfoview.cpp.o
In file included from /home/kwijt/.cache/aur/bp-nfoview/src/bp-nfoview-0.2.0/src/bp-nfoview.cpp:32:0:
/home/kwijt/.cache/aur/bp-nfoview/src/bp-nfoview-0.2.0/src/BPNVMainWindow.hpp:67:19: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
  QSize sizeHint() const override;
                   ^
/home/kwijt/.cache/aur/bp-nfoview/src/bp-nfoview-0.2.0/src/BPNVMainWindow.hpp:71:7: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
  std::shared_ptr<QByteArray> rawFileData;
       ^
src/CMakeFiles/bp-nfoview.dir/build.make:62: recipe for target 'src/CMakeFiles/bp-nfoview.dir/bp-nfoview.cpp.o' failed
make[2]: **\* [src/CMakeFiles/bp-nfoview.dir/bp-nfoview.cpp.o] Error 1
CMakeFiles/Makefile2:86: recipe for target 'src/CMakeFiles/bp-nfoview.dir/all' failed
make[1]: **\* [src/CMakeFiles/bp-nfoview.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by brainpower** [comment]
Sorry, didn't notice since C++11 is the standard C++ with GCC 6.

I'll add the -std=c++11 switch.
