### ISSUE TITLE
bp-nfoview" received signal SIGSEGV, Segmentation fault

### ISSUE THREAD

**Issue by ghost** [brainpower/bp-nfoview#4]
Hello brainpower.

I got this in dmesg.
traps: bp-nfoview[7397] general protection ip:7f098273167b sp:7ffd3903d6c0 error:0
[38612.209855]  in libQt5Core.so.5.7.1[7f09824c3000+457000]

bp-nfoview[16526]: segfault at 2200000034 ip 00007fdf2f50743b sp 00007ffd49e86640 error 4 in libQt5Core.so.5.7.1[7fdf2f26d000+4a0000

And i start to debug the application and got this.

Thread 1 "bp-nfoview" received signal SIGSEGV, Segmentation fault.
0x00007ffff710143b in QCoreGlobalData::~QCoreGlobalData (
    this=0x7ffff7317a60 <(anonymous namespace)::Q_QGS_globalInstance::innerFunction()::holder>, 
    __in_chrg=<optimized out>) at kernel/qcoreglobaldata.cpp:56
56	kernel/qcoreglobaldata.cpp: No such file or directory.

Is this something obvious to you?? 

Added new info:
If i start bp-nfoview the application starts fine and behave just like it should, but as soon i open an nfofile
i got this output in dmesg.

bp-nfoview[3160]: segfault at 2200000034 ip 00007f4367fc667b sp 00007fffbcf631b0 error 4 in libQt5Core.so.5.7.1[7f4367d58000+457000]

Update:1
I testing bp-nfoview in arch linux,and this is what happens.
1. starting application(works fine)
2. open an nfofile(working fine)
3. close application and got this output in dmesg
bp-nfoview[874]: segfault at 0 ip  (null) sp 00007ffeecb21f08 error 14 in bp-nfoview[400000+12000].

[gdb.txt](https://github.com/brainpower/bp-nfoview/files/903597/gdb.txt)

[bp-error.txt](https://github.com/brainpower/bp-nfoview/files/903599/bp-error.txt)

First i thought it was qtwidgets that was the problem,but seems to be something else. And that i have same problem on two different systems arch with xfce and gentoo with plasma.
I should say the application working fine all the time on both systems so no problem there.

**Comment by brainpower** [comment]
I've got the same crash, noticed that some time ago, investigated a little like you did, but couldn't find the reason or a solution quickly.
Since the viewers functionality isn't broken by this, I didn't give it a high priority...

If I remember correctly at that time the crash only happened if you actually load a file, if you didn't it wouldn't crash when quitting.
I've got time to look into it again in a few days...

**Comment by brainpower** [comment]
Fix in master, will make a release later.
